# Generated by Django 4.2.28 on 2026-06-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_multi_boutiques'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='users', to='shops.shop', verbose_name='Boutiques assignées'),
        ),
    ]
