# Generated by Django 4.2.28 on 2026-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='tagline',
            field=models.CharField(blank=True, default='Gestion commerciale multi-secteurs', max_length=200),
        ),
    ]
