# Generated by Django 4.2.28 on 2026-06-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_multi_boutiques'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shop', 'name')},
        ),
    ]
